# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1543y2wTJVh2b4Z3GvtfDsdyzd6hnv_QN
"""

n=22
print("You have 9 Guesses")
for i in range(1,10):
  num=int(input("Guess the number"))
  if num==n:
    print("Yeh! Good job Buddy.You won")
    break
  elif num>n:
    print("Enter the smaller number")
  elif num<n:
    print("Enter the larger number")
else:
  print("Game over")



